### ISSUE TITLE
ENH: support per-frontend extra requirements with pip

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4270]
Most users only need a single frontend, but many frontends have optional dependencies (`h5py`, `netcdf4`, `f90nml` ...), which are not exactly documented. The lazy-import mechanism helps discovering missing bits, but only at runtime.

It'd be cool to support installing yt with all optional requirements approriate for a specific frontend, for instance
```
python -m pip install "yt[enzo]"
```
would install `h5py` directly.

### Caveats (and solutions)
A challenge with doing this is to avoid duplicating constraints as much as possible.
Leveraging pip's support for recursive dependencies (unfortunately poorly documented, but known via https://hynek.me/articles/python-recursive-optional-dependencies/), repetitions can be avoided. Here's a example of how it might work

```toml
[project.optional-dependencies]
# generic requirements
HDF5 = ["h5py>=3.0"]
fortran = ["f90nml>=1.1.2"]

# frontend-specific requirements
enzo = ["yt[HDF5]"]
owls = ["yt[HDF5]"]
ramses = ["yt[fortran]"]

# refactor existing "full" target
full = ["yt[enzo, owls, ramses]"]
```

Note that I'm using `pyproject.toml`'s format, while currently our metadata lives in `setup.cfg`. Recursive dependencies are also available in `setup.cfg` but it's destined to be deprecated (see https://github.com/pypa/setuptools/issues/3214), so might as well migrate to `pyproject.toml` while we are at it.

Also note that recursive dependencies require `pip>=21.2`, so it doesn't work out of the box for Python versions with a bundled pip version older than this. For reference, here's a manually collected sample dataset

| Python version | bundled pip version |
| :---------------: | :-------------------: |  
| 3.8.0 | 19.2.3 |
| 3.8.13 | 22.0.4 |
| 3.9.0 | 20.2.3 |
| 3.9.7 | 21.2.3 |
| 3.10.0 | 21.2.3 |

So in order to support this for any patch version of Python 3.8 and 3.9, we'd need to specifically instruct upgrading `pip` itself as part of the installation process, and this extra step can be dropped when we stop supporting versions older than `3.9.7` (so, basically, when we drop Python 3.9, most likely in 2024 at the current pace)
