### ISSUE TITLE
MNT: enable auto-updates for GHA with dependabot ?

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt#4333]
We usually only upgrade GitHub Actions in our workflows manually, sometimes in response to deprecation warnings (#4076, #4290), or just as a routine housekeeping task (#3923, #4076, #4151).
In any case, it's a bit annoying to have to do this manually, and [it can be avoided using dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot), which has been integrated into GitHub itself.

I'd like to propose we enable it.

I've tested it on my personal projects, and all it takes is a small configuration file (`.github/dependabot.yml`)

```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: /.github/workflows
  schedule:
    interval: monthly
```

Any thoughts ?
