### ISSUE TITLE
Pyright flags `load` as `reportPrivateImportUsage`

### ISSUE THREAD

**Issue by edran** [yt-project/yt#4683]
### Bug report

**Bug summary**

Pyright flags any usage of `load` as `reportPrivateImportUsage`. I believe it's because `load` and other such functions are not exported as public in `yt/__init__.py`.

**Code for reproduction**

Example `pyproject.toml` with `poetry`-controlled deps:

```toml
[tool.poetry]
name = "foo"
version = "0.1.0"
description = ""
authors = ["foo"]
packages = [{include = "foo"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
yt = "^4.2.2"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.329"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
```

Error can be reproduced with the following snippet:

```python
import yt
yt.load("")
```

`poetry run pip freeze` output:

```python
appnope==0.1.3
asttokens==2.4.0
backcall==0.2.0
cmyt==1.4.0
comm==0.1.4
contourpy==1.1.1
cycler==0.12.0
decorator==5.1.1
ewah-bool-utils==1.1.0
executing==2.0.0
fonttools==4.43.0
ipython==8.16.1
ipywidgets==8.1.1
jedi==0.19.1
jupyterlab-widgets==3.0.9
kiwisolver==1.4.5
matplotlib==3.8.0
matplotlib-inline==0.1.6
more-itertools==10.1.0
mpmath==1.3.0
nodeenv==1.8.0
numpy==1.26.0
packaging==23.2
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.1
prompt-toolkit==3.0.39
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.16.1
pyparsing==3.1.1
pyright==1.1.329
python-dateutil==2.8.2
setuptools-scm==8.0.4
six==1.16.0
stack-data==0.6.3
sympy==1.12
tomli_w==1.0.0
tqdm==4.66.1
traitlets==5.11.2
typing_extensions==4.8.0
unyt==2.9.5
wcwidth==0.2.8
widgetsnbextension==4.0.9
yt==4.2.2
``` 

**Actual outcome**

```
$ cat foo.py
import yt
yt.load("")
$ poetry run pyright
/path/to/foo.py
  /path/to/foo.py:3:4 - error: "load" is not exported from module "yt" (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations
```

**Expected outcome**

No error from `pyright`.

**Version Information**

  * Operating System: MacOS 12.6.2
  * Python Version: 3.11
  * yt version: 4.2.2
  * Other Libraries (if applicable): N/A
