### ISSUE TITLE
BUG: Segfault in smoothing length calculation on Mac

### ISSUE THREAD

**Issue by nastasha-w** [yt-project/yt#4961]
### Bug report

**Bug summary**

I get a segfault when loading the Tipsy 00300 galaxy into `yt`. From the output, this seems to occur when `yt` tries to calculate smoothing lengths. 

The KDTree construction before the smoothing length computation seems to work. This issue occurred on my Mac both with numpy 1.26, and with the bleeding-edge numpy version. The error reminded me of #4953, but that issue was marked resolved after an upstream fix in numpy. 

**Code for reproduction**
This issue was triggered when analyzing the [Tipsy galaxy 00300](https://hub.yt/#item/579fb0a77b6f0800011ea19f) from the yt hub.

```python
import yt
sampledatadir = "/Users/nastasha/code/ytdev_misc/sample_data/"
datasetn = sampledatadir + "TipsyGalaxy/galaxy.00300"
ds = yt.load(datasetn)
```

**Actual outcome**

```
yt : [INFO     ] 2024-08-01 16:53:46,619 Parameters: current_time              = 20.100000000000044
yt : [INFO     ] 2024-08-01 16:53:46,620 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2024-08-01 16:53:46,621 Parameters: domain_left_edge          = None
yt : [INFO     ] 2024-08-01 16:53:46,621 Parameters: domain_right_edge         = None
yt : [INFO     ] 2024-08-01 16:53:46,621 Parameters: cosmological_simulation   = 0.0
yt : [INFO     ] 2024-08-01 16:53:46,634 Loading KDTree from galaxy.00300.kdtree
Generate smoothing length:   0%|                                            | 0/76962 [00:00<?, ?it/s]zsh: segmentation fault  ipython
(ytdev) nastasha@dhcp-165-124-148-182 ytdev_misc % /Users/nastasha/opt/anaconda3/envs/ytdev/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Expected outcome**

A loaded `yt` dataset, with smoothing lengths for the SPH particles.

**Version Information**

  * Operating System: M1 Mac, Sonoma 14.5 (23F79)
  * Python Version: 3.12.4 (also occurred in an older environment with python 3.11 and numpy 1.26)
  * yt version: 4.4.dev0 (main branch in my git repo, synced with yt main on 2024-08-01)
  * environment setup: (from the yt top directory)
    ```bash
    conda create -n ytdev python=3.12 pip 
    conda activate ytdev
    python -m pip install git+https://github.com/numpy/numpy.git
    python -m pip install -e ".[doc]"
    python -m pip install h5py pandas
    ```

**Comment by nastasha-w** [comment]
update: I tried to run the same thing on the university linux cluster, and after many frustrations getting `yt` installed, I got the same error running the same code, except without any text after `segmentation fault`. This doesn't seem to be OS-specific.

Details of the linux setup:
* OS: Red Hat Enterprise Linux 7.9 (according to the system webpage)
* python: 3.12.3
* yt: 4.4.dev0 (main branch on 2024-08-01)
* yt installation: 
  * conda environment specifying python 3.12, from .yaml file:
    ```
    channels:
      - defaults
      - conda-forge
    dependencies:
      - python=3.12
      - astropy
      - numpy
        - pandas
        - scipy
        - h5py
        - ipython
        - matplotlib
        - more-itertools
        - cython
        - mpi4py
        - pytest
        - unyt
        - pip 
      variables:
        MPLBACKEND: TkAgg
      # MPLBACKEND needs to be set on Quest; might not be an issue on other systems
     ```
  * `yt` from the git main branch
  * `python -m pip install .` in the `yt` top-level directory
  * for the pip installation, I had to load a non-default `gcc` version on this system. `gcc/11.2.0` worked, the default gcc version 4.8.5 threw an error when I tried to pip install.
